//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASU_E_Commerce.Service1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sign_upOperationCompleted;
        
        private System.Threading.SendOrPostCallback sign_inOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_user_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback edit_user_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback edit_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_bookOperationCompleted;
        
        private System.Threading.SendOrPostCallback book_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback list_productsOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_shirtsOperationCompleted;
        
        private System.Threading.SendOrPostCallback edit_shirtOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_shirtOperationCompleted;
        
        private System.Threading.SendOrPostCallback shirt_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_cartOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkProductExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkCurrentQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkCurrentPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback quantityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ASU_E_Commerce.Properties.Settings.Default.ASU_E_Commerce_Service1_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sign_upCompletedEventHandler sign_upCompleted;
        
        /// <remarks/>
        public event sign_inCompletedEventHandler sign_inCompleted;
        
        /// <remarks/>
        public event get_user_infoCompletedEventHandler get_user_infoCompleted;
        
        /// <remarks/>
        public event edit_user_infoCompletedEventHandler edit_user_infoCompleted;
        
        /// <remarks/>
        public event add_booksCompletedEventHandler add_booksCompleted;
        
        /// <remarks/>
        public event edit_booksCompletedEventHandler edit_booksCompleted;
        
        /// <remarks/>
        public event delete_bookCompletedEventHandler delete_bookCompleted;
        
        /// <remarks/>
        public event book_detailsCompletedEventHandler book_detailsCompleted;
        
        /// <remarks/>
        public event search_booksCompletedEventHandler search_booksCompleted;
        
        /// <remarks/>
        public event list_productsCompletedEventHandler list_productsCompleted;
        
        /// <remarks/>
        public event add_shirtsCompletedEventHandler add_shirtsCompleted;
        
        /// <remarks/>
        public event edit_shirtCompletedEventHandler edit_shirtCompleted;
        
        /// <remarks/>
        public event delete_shirtCompletedEventHandler delete_shirtCompleted;
        
        /// <remarks/>
        public event shirt_detailsCompletedEventHandler shirt_detailsCompleted;
        
        /// <remarks/>
        public event add_cartCompletedEventHandler add_cartCompleted;
        
        /// <remarks/>
        public event checkProductExistsCompletedEventHandler checkProductExistsCompleted;
        
        /// <remarks/>
        public event checkCurrentQuantityCompletedEventHandler checkCurrentQuantityCompleted;
        
        /// <remarks/>
        public event checkCurrentPriceCompletedEventHandler checkCurrentPriceCompleted;
        
        /// <remarks/>
        public event product_listCompletedEventHandler product_listCompleted;
        
        /// <remarks/>
        public event quantityCompletedEventHandler quantityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sign_up", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sign_up([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string street1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string street2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string state, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string zip, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("sign_up", new object[] {
                        fname,
                        lname,
                        pname,
                        email,
                        id,
                        pword,
                        street1,
                        street2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sign_upAsync(string fname, string lname, string pname, string email, string id, string pword, string street1, string street2, string city, string state, string zip, string host_email, string host_credential) {
            this.sign_upAsync(fname, lname, pname, email, id, pword, street1, street2, city, state, zip, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void sign_upAsync(string fname, string lname, string pname, string email, string id, string pword, string street1, string street2, string city, string state, string zip, string host_email, string host_credential, object userState) {
            if ((this.sign_upOperationCompleted == null)) {
                this.sign_upOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsign_upOperationCompleted);
            }
            this.InvokeAsync("sign_up", new object[] {
                        fname,
                        lname,
                        pname,
                        email,
                        id,
                        pword,
                        street1,
                        street2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential}, this.sign_upOperationCompleted, userState);
        }
        
        private void Onsign_upOperationCompleted(object arg) {
            if ((this.sign_upCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sign_upCompleted(this, new sign_upCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sign_in", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sign_in([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("sign_in", new object[] {
                        id,
                        pword,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sign_inAsync(string id, string pword, string host_email, string host_credential) {
            this.sign_inAsync(id, pword, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void sign_inAsync(string id, string pword, string host_email, string host_credential, object userState) {
            if ((this.sign_inOperationCompleted == null)) {
                this.sign_inOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsign_inOperationCompleted);
            }
            this.InvokeAsync("sign_in", new object[] {
                        id,
                        pword,
                        host_email,
                        host_credential}, this.sign_inOperationCompleted, userState);
        }
        
        private void Onsign_inOperationCompleted(object arg) {
            if ((this.sign_inCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sign_inCompleted(this, new sign_inCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/get_user_info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] get_user_info([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("get_user_info", new object[] {
                        login,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_user_infoAsync(string login, string host_email, string host_credential) {
            this.get_user_infoAsync(login, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void get_user_infoAsync(string login, string host_email, string host_credential, object userState) {
            if ((this.get_user_infoOperationCompleted == null)) {
                this.get_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_user_infoOperationCompleted);
            }
            this.InvokeAsync("get_user_info", new object[] {
                        login,
                        host_email,
                        host_credential}, this.get_user_infoOperationCompleted, userState);
        }
        
        private void Onget_user_infoOperationCompleted(object arg) {
            if ((this.get_user_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_user_infoCompleted(this, new get_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/edit_user_info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string edit_user_info([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loginid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string n_pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rn_pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string st_addr1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string st_addr2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string state, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string zip, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("edit_user_info", new object[] {
                        userid,
                        pname,
                        email,
                        loginid,
                        n_pword,
                        rn_pword,
                        st_addr1,
                        st_addr2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void edit_user_infoAsync(string userid, string pname, string email, string loginid, string n_pword, string rn_pword, string st_addr1, string st_addr2, string city, string state, string zip, string host_email, string host_credential) {
            this.edit_user_infoAsync(userid, pname, email, loginid, n_pword, rn_pword, st_addr1, st_addr2, city, state, zip, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void edit_user_infoAsync(string userid, string pname, string email, string loginid, string n_pword, string rn_pword, string st_addr1, string st_addr2, string city, string state, string zip, string host_email, string host_credential, object userState) {
            if ((this.edit_user_infoOperationCompleted == null)) {
                this.edit_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onedit_user_infoOperationCompleted);
            }
            this.InvokeAsync("edit_user_info", new object[] {
                        userid,
                        pname,
                        email,
                        loginid,
                        n_pword,
                        rn_pword,
                        st_addr1,
                        st_addr2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential}, this.edit_user_infoOperationCompleted, userState);
        }
        
        private void Onedit_user_infoOperationCompleted(object arg) {
            if ((this.edit_user_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.edit_user_infoCompleted(this, new edit_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/add_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string add_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string isbn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("add_books", new object[] {
                        login_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_booksAsync(string login_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential) {
            this.add_booksAsync(login_id, isbn, title, subject, quantity, price, bidding, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void add_booksAsync(string login_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential, object userState) {
            if ((this.add_booksOperationCompleted == null)) {
                this.add_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_booksOperationCompleted);
            }
            this.InvokeAsync("add_books", new object[] {
                        login_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential}, this.add_booksOperationCompleted, userState);
        }
        
        private void Onadd_booksOperationCompleted(object arg) {
            if ((this.add_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_booksCompleted(this, new add_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/edit_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string edit_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string product_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string isbn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("edit_books", new object[] {
                        product_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void edit_booksAsync(string product_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential) {
            this.edit_booksAsync(product_id, isbn, title, subject, quantity, price, bidding, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void edit_booksAsync(string product_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential, object userState) {
            if ((this.edit_booksOperationCompleted == null)) {
                this.edit_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onedit_booksOperationCompleted);
            }
            this.InvokeAsync("edit_books", new object[] {
                        product_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential}, this.edit_booksOperationCompleted, userState);
        }
        
        private void Onedit_booksOperationCompleted(object arg) {
            if ((this.edit_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.edit_booksCompleted(this, new edit_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete_book", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string delete_book([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("delete_book", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_bookAsync(string productid, string host_email, string host_credential) {
            this.delete_bookAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void delete_bookAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.delete_bookOperationCompleted == null)) {
                this.delete_bookOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_bookOperationCompleted);
            }
            this.InvokeAsync("delete_book", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.delete_bookOperationCompleted, userState);
        }
        
        private void Ondelete_bookOperationCompleted(object arg) {
            if ((this.delete_bookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_bookCompleted(this, new delete_bookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/book_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] book_details([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("book_details", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void book_detailsAsync(string productid, string host_email, string host_credential) {
            this.book_detailsAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void book_detailsAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.book_detailsOperationCompleted == null)) {
                this.book_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onbook_detailsOperationCompleted);
            }
            this.InvokeAsync("book_details", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.book_detailsOperationCompleted, userState);
        }
        
        private void Onbook_detailsOperationCompleted(object arg) {
            if ((this.book_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.book_detailsCompleted(this, new book_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/search_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] search_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string input, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("search_books", new object[] {
                        type,
                        input,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void search_booksAsync(string type, string input, string host_email, string host_credential) {
            this.search_booksAsync(type, input, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void search_booksAsync(string type, string input, string host_email, string host_credential, object userState) {
            if ((this.search_booksOperationCompleted == null)) {
                this.search_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_booksOperationCompleted);
            }
            this.InvokeAsync("search_books", new object[] {
                        type,
                        input,
                        host_email,
                        host_credential}, this.search_booksOperationCompleted, userState);
        }
        
        private void Onsearch_booksOperationCompleted(object arg) {
            if ((this.search_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_booksCompleted(this, new search_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/list_products", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] list_products([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("list_products", new object[] {
                        id,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void list_productsAsync(string id, string host_email, string host_credential) {
            this.list_productsAsync(id, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void list_productsAsync(string id, string host_email, string host_credential, object userState) {
            if ((this.list_productsOperationCompleted == null)) {
                this.list_productsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlist_productsOperationCompleted);
            }
            this.InvokeAsync("list_products", new object[] {
                        id,
                        host_email,
                        host_credential}, this.list_productsOperationCompleted, userState);
        }
        
        private void Onlist_productsOperationCompleted(object arg) {
            if ((this.list_productsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.list_productsCompleted(this, new list_productsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/add_shirts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string add_shirts([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string brand, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string size, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string color, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string material, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agegroup, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("add_shirts", new object[] {
                        brand,
                        size,
                        color,
                        material,
                        gender,
                        agegroup,
                        quantity,
                        price,
                        bidding,
                        userid,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_shirtsAsync(string brand, string size, string color, string material, string gender, string agegroup, string quantity, string price, string bidding, string userid, string host_email, string host_credential) {
            this.add_shirtsAsync(brand, size, color, material, gender, agegroup, quantity, price, bidding, userid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void add_shirtsAsync(string brand, string size, string color, string material, string gender, string agegroup, string quantity, string price, string bidding, string userid, string host_email, string host_credential, object userState) {
            if ((this.add_shirtsOperationCompleted == null)) {
                this.add_shirtsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_shirtsOperationCompleted);
            }
            this.InvokeAsync("add_shirts", new object[] {
                        brand,
                        size,
                        color,
                        material,
                        gender,
                        agegroup,
                        quantity,
                        price,
                        bidding,
                        userid,
                        host_email,
                        host_credential}, this.add_shirtsOperationCompleted, userState);
        }
        
        private void Onadd_shirtsOperationCompleted(object arg) {
            if ((this.add_shirtsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_shirtsCompleted(this, new add_shirtsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/edit_shirt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string edit_shirt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string brand, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string size, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string color, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string material, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agegroup, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string image1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string image2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("edit_shirt", new object[] {
                        productid,
                        brand,
                        size,
                        color,
                        material,
                        gender,
                        agegroup,
                        quantity,
                        price,
                        bidding,
                        image1,
                        image2,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void edit_shirtAsync(string productid, string brand, string size, string color, string material, string gender, string agegroup, string quantity, string price, string bidding, string image1, string image2, string host_email, string host_credential) {
            this.edit_shirtAsync(productid, brand, size, color, material, gender, agegroup, quantity, price, bidding, image1, image2, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void edit_shirtAsync(string productid, string brand, string size, string color, string material, string gender, string agegroup, string quantity, string price, string bidding, string image1, string image2, string host_email, string host_credential, object userState) {
            if ((this.edit_shirtOperationCompleted == null)) {
                this.edit_shirtOperationCompleted = new System.Threading.SendOrPostCallback(this.Onedit_shirtOperationCompleted);
            }
            this.InvokeAsync("edit_shirt", new object[] {
                        productid,
                        brand,
                        size,
                        color,
                        material,
                        gender,
                        agegroup,
                        quantity,
                        price,
                        bidding,
                        image1,
                        image2,
                        host_email,
                        host_credential}, this.edit_shirtOperationCompleted, userState);
        }
        
        private void Onedit_shirtOperationCompleted(object arg) {
            if ((this.edit_shirtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.edit_shirtCompleted(this, new edit_shirtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete_shirt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string delete_shirt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("delete_shirt", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_shirtAsync(string productid, string host_email, string host_credential) {
            this.delete_shirtAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void delete_shirtAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.delete_shirtOperationCompleted == null)) {
                this.delete_shirtOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_shirtOperationCompleted);
            }
            this.InvokeAsync("delete_shirt", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.delete_shirtOperationCompleted, userState);
        }
        
        private void Ondelete_shirtOperationCompleted(object arg) {
            if ((this.delete_shirtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_shirtCompleted(this, new delete_shirtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/shirt_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] shirt_details([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("shirt_details", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void shirt_detailsAsync(string productid, string host_email, string host_credential) {
            this.shirt_detailsAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void shirt_detailsAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.shirt_detailsOperationCompleted == null)) {
                this.shirt_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onshirt_detailsOperationCompleted);
            }
            this.InvokeAsync("shirt_details", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.shirt_detailsOperationCompleted, userState);
        }
        
        private void Onshirt_detailsOperationCompleted(object arg) {
            if ((this.shirt_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shirt_detailsCompleted(this, new shirt_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/add_cart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string add_cart([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("add_cart", new object[] {
                        userid,
                        productid,
                        quantity,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_cartAsync(string userid, string productid, string quantity, string host_email, string host_credential) {
            this.add_cartAsync(userid, productid, quantity, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void add_cartAsync(string userid, string productid, string quantity, string host_email, string host_credential, object userState) {
            if ((this.add_cartOperationCompleted == null)) {
                this.add_cartOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_cartOperationCompleted);
            }
            this.InvokeAsync("add_cart", new object[] {
                        userid,
                        productid,
                        quantity,
                        host_email,
                        host_credential}, this.add_cartOperationCompleted, userState);
        }
        
        private void Onadd_cartOperationCompleted(object arg) {
            if ((this.add_cartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_cartCompleted(this, new add_cartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/checkProductExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void checkProductExists([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential, out bool checkProductExistsResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool checkProductExistsResultSpecified) {
            object[] results = this.Invoke("checkProductExists", new object[] {
                        productid,
                        host_email,
                        host_credential});
            checkProductExistsResult = ((bool)(results[0]));
            checkProductExistsResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void checkProductExistsAsync(string productid, string host_email, string host_credential) {
            this.checkProductExistsAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void checkProductExistsAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.checkProductExistsOperationCompleted == null)) {
                this.checkProductExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckProductExistsOperationCompleted);
            }
            this.InvokeAsync("checkProductExists", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.checkProductExistsOperationCompleted, userState);
        }
        
        private void OncheckProductExistsOperationCompleted(object arg) {
            if ((this.checkProductExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkProductExistsCompleted(this, new checkProductExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/checkCurrentQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string checkCurrentQuantity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("checkCurrentQuantity", new object[] {
                        productid,
                        quantity,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkCurrentQuantityAsync(string productid, string quantity, string host_email, string host_credential) {
            this.checkCurrentQuantityAsync(productid, quantity, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void checkCurrentQuantityAsync(string productid, string quantity, string host_email, string host_credential, object userState) {
            if ((this.checkCurrentQuantityOperationCompleted == null)) {
                this.checkCurrentQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckCurrentQuantityOperationCompleted);
            }
            this.InvokeAsync("checkCurrentQuantity", new object[] {
                        productid,
                        quantity,
                        host_email,
                        host_credential}, this.checkCurrentQuantityOperationCompleted, userState);
        }
        
        private void OncheckCurrentQuantityOperationCompleted(object arg) {
            if ((this.checkCurrentQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkCurrentQuantityCompleted(this, new checkCurrentQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/checkCurrentPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string checkCurrentPrice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("checkCurrentPrice", new object[] {
                        productid,
                        price,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkCurrentPriceAsync(string productid, string price, string host_email, string host_credential) {
            this.checkCurrentPriceAsync(productid, price, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void checkCurrentPriceAsync(string productid, string price, string host_email, string host_credential, object userState) {
            if ((this.checkCurrentPriceOperationCompleted == null)) {
                this.checkCurrentPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckCurrentPriceOperationCompleted);
            }
            this.InvokeAsync("checkCurrentPrice", new object[] {
                        productid,
                        price,
                        host_email,
                        host_credential}, this.checkCurrentPriceOperationCompleted, userState);
        }
        
        private void OncheckCurrentPriceOperationCompleted(object arg) {
            if ((this.checkCurrentPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkCurrentPriceCompleted(this, new checkCurrentPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/product_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] product_list([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("product_list", new object[] {
                        userid,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void product_listAsync(string userid, string host_email, string host_credential) {
            this.product_listAsync(userid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void product_listAsync(string userid, string host_email, string host_credential, object userState) {
            if ((this.product_listOperationCompleted == null)) {
                this.product_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_listOperationCompleted);
            }
            this.InvokeAsync("product_list", new object[] {
                        userid,
                        host_email,
                        host_credential}, this.product_listOperationCompleted, userState);
        }
        
        private void Onproduct_listOperationCompleted(object arg) {
            if ((this.product_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_listCompleted(this, new product_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/quantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] quantity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credentials) {
            object[] results = this.Invoke("quantity", new object[] {
                        userid,
                        host_email,
                        host_credentials});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void quantityAsync(string userid, string host_email, string host_credentials) {
            this.quantityAsync(userid, host_email, host_credentials, null);
        }
        
        /// <remarks/>
        public void quantityAsync(string userid, string host_email, string host_credentials, object userState) {
            if ((this.quantityOperationCompleted == null)) {
                this.quantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquantityOperationCompleted);
            }
            this.InvokeAsync("quantity", new object[] {
                        userid,
                        host_email,
                        host_credentials}, this.quantityOperationCompleted, userState);
        }
        
        private void OnquantityOperationCompleted(object arg) {
            if ((this.quantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quantityCompleted(this, new quantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sign_upCompletedEventHandler(object sender, sign_upCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sign_upCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sign_upCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sign_inCompletedEventHandler(object sender, sign_inCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sign_inCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sign_inCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void get_user_infoCompletedEventHandler(object sender, get_user_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void edit_user_infoCompletedEventHandler(object sender, edit_user_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class edit_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal edit_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void add_booksCompletedEventHandler(object sender, add_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void edit_booksCompletedEventHandler(object sender, edit_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class edit_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal edit_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void delete_bookCompletedEventHandler(object sender, delete_bookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_bookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_bookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void book_detailsCompletedEventHandler(object sender, book_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class book_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal book_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void search_booksCompletedEventHandler(object sender, search_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void list_productsCompletedEventHandler(object sender, list_productsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class list_productsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal list_productsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void add_shirtsCompletedEventHandler(object sender, add_shirtsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_shirtsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_shirtsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void edit_shirtCompletedEventHandler(object sender, edit_shirtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class edit_shirtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal edit_shirtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void delete_shirtCompletedEventHandler(object sender, delete_shirtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_shirtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_shirtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void shirt_detailsCompletedEventHandler(object sender, shirt_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shirt_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shirt_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void add_cartCompletedEventHandler(object sender, add_cartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_cartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_cartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void checkProductExistsCompletedEventHandler(object sender, checkProductExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkProductExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkProductExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool checkProductExistsResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool checkProductExistsResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void checkCurrentQuantityCompletedEventHandler(object sender, checkCurrentQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkCurrentQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkCurrentQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void checkCurrentPriceCompletedEventHandler(object sender, checkCurrentPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkCurrentPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkCurrentPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void product_listCompletedEventHandler(object sender, product_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void quantityCompletedEventHandler(object sender, quantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591