//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASU_E_Commerce.Service1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sign_upOperationCompleted;
        
        private System.Threading.SendOrPostCallback sign_inOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_user_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback edit_user_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback edit_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_bookOperationCompleted;
        
        private System.Threading.SendOrPostCallback book_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_booksOperationCompleted;
        
        private System.Threading.SendOrPostCallback list_productsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ASU_E_Commerce.Properties.Settings.Default.ASU_E_Commerce_Service1_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sign_upCompletedEventHandler sign_upCompleted;
        
        /// <remarks/>
        public event sign_inCompletedEventHandler sign_inCompleted;
        
        /// <remarks/>
        public event get_user_infoCompletedEventHandler get_user_infoCompleted;
        
        /// <remarks/>
        public event edit_user_infoCompletedEventHandler edit_user_infoCompleted;
        
        /// <remarks/>
        public event add_booksCompletedEventHandler add_booksCompleted;
        
        /// <remarks/>
        public event edit_booksCompletedEventHandler edit_booksCompleted;
        
        /// <remarks/>
        public event delete_bookCompletedEventHandler delete_bookCompleted;
        
        /// <remarks/>
        public event book_detailsCompletedEventHandler book_detailsCompleted;
        
        /// <remarks/>
        public event search_booksCompletedEventHandler search_booksCompleted;
        
        /// <remarks/>
        public event list_productsCompletedEventHandler list_productsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sign_up", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sign_up([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string street1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string street2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string state, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string zip, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("sign_up", new object[] {
                        fname,
                        lname,
                        pname,
                        email,
                        id,
                        pword,
                        street1,
                        street2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sign_upAsync(string fname, string lname, string pname, string email, string id, string pword, string street1, string street2, string city, string state, string zip, string host_email, string host_credential) {
            this.sign_upAsync(fname, lname, pname, email, id, pword, street1, street2, city, state, zip, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void sign_upAsync(string fname, string lname, string pname, string email, string id, string pword, string street1, string street2, string city, string state, string zip, string host_email, string host_credential, object userState) {
            if ((this.sign_upOperationCompleted == null)) {
                this.sign_upOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsign_upOperationCompleted);
            }
            this.InvokeAsync("sign_up", new object[] {
                        fname,
                        lname,
                        pname,
                        email,
                        id,
                        pword,
                        street1,
                        street2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential}, this.sign_upOperationCompleted, userState);
        }
        
        private void Onsign_upOperationCompleted(object arg) {
            if ((this.sign_upCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sign_upCompleted(this, new sign_upCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/sign_in", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] sign_in([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("sign_in", new object[] {
                        id,
                        pword,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sign_inAsync(string id, string pword, string host_email, string host_credential) {
            this.sign_inAsync(id, pword, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void sign_inAsync(string id, string pword, string host_email, string host_credential, object userState) {
            if ((this.sign_inOperationCompleted == null)) {
                this.sign_inOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsign_inOperationCompleted);
            }
            this.InvokeAsync("sign_in", new object[] {
                        id,
                        pword,
                        host_email,
                        host_credential}, this.sign_inOperationCompleted, userState);
        }
        
        private void Onsign_inOperationCompleted(object arg) {
            if ((this.sign_inCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sign_inCompleted(this, new sign_inCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/get_user_info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] get_user_info([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("get_user_info", new object[] {
                        login,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_user_infoAsync(string login, string host_email, string host_credential) {
            this.get_user_infoAsync(login, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void get_user_infoAsync(string login, string host_email, string host_credential, object userState) {
            if ((this.get_user_infoOperationCompleted == null)) {
                this.get_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_user_infoOperationCompleted);
            }
            this.InvokeAsync("get_user_info", new object[] {
                        login,
                        host_email,
                        host_credential}, this.get_user_infoOperationCompleted, userState);
        }
        
        private void Onget_user_infoOperationCompleted(object arg) {
            if ((this.get_user_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_user_infoCompleted(this, new get_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/edit_user_info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string edit_user_info([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loginid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string n_pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rn_pword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string st_addr1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string st_addr2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string state, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string zip, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("edit_user_info", new object[] {
                        userid,
                        pname,
                        email,
                        loginid,
                        n_pword,
                        rn_pword,
                        st_addr1,
                        st_addr2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void edit_user_infoAsync(string userid, string pname, string email, string loginid, string n_pword, string rn_pword, string st_addr1, string st_addr2, string city, string state, string zip, string host_email, string host_credential) {
            this.edit_user_infoAsync(userid, pname, email, loginid, n_pword, rn_pword, st_addr1, st_addr2, city, state, zip, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void edit_user_infoAsync(string userid, string pname, string email, string loginid, string n_pword, string rn_pword, string st_addr1, string st_addr2, string city, string state, string zip, string host_email, string host_credential, object userState) {
            if ((this.edit_user_infoOperationCompleted == null)) {
                this.edit_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onedit_user_infoOperationCompleted);
            }
            this.InvokeAsync("edit_user_info", new object[] {
                        userid,
                        pname,
                        email,
                        loginid,
                        n_pword,
                        rn_pword,
                        st_addr1,
                        st_addr2,
                        city,
                        state,
                        zip,
                        host_email,
                        host_credential}, this.edit_user_infoOperationCompleted, userState);
        }
        
        private void Onedit_user_infoOperationCompleted(object arg) {
            if ((this.edit_user_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.edit_user_infoCompleted(this, new edit_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/add_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string add_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string isbn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("add_books", new object[] {
                        login_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_booksAsync(string login_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential) {
            this.add_booksAsync(login_id, isbn, title, subject, quantity, price, bidding, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void add_booksAsync(string login_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential, object userState) {
            if ((this.add_booksOperationCompleted == null)) {
                this.add_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_booksOperationCompleted);
            }
            this.InvokeAsync("add_books", new object[] {
                        login_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential}, this.add_booksOperationCompleted, userState);
        }
        
        private void Onadd_booksOperationCompleted(object arg) {
            if ((this.add_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_booksCompleted(this, new add_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/edit_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string edit_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string product_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string isbn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bidding, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("edit_books", new object[] {
                        product_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void edit_booksAsync(string product_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential) {
            this.edit_booksAsync(product_id, isbn, title, subject, quantity, price, bidding, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void edit_booksAsync(string product_id, string isbn, string title, string subject, string quantity, string price, string bidding, string host_email, string host_credential, object userState) {
            if ((this.edit_booksOperationCompleted == null)) {
                this.edit_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onedit_booksOperationCompleted);
            }
            this.InvokeAsync("edit_books", new object[] {
                        product_id,
                        isbn,
                        title,
                        subject,
                        quantity,
                        price,
                        bidding,
                        host_email,
                        host_credential}, this.edit_booksOperationCompleted, userState);
        }
        
        private void Onedit_booksOperationCompleted(object arg) {
            if ((this.edit_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.edit_booksCompleted(this, new edit_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete_book", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string delete_book([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("delete_book", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_bookAsync(string productid, string host_email, string host_credential) {
            this.delete_bookAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void delete_bookAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.delete_bookOperationCompleted == null)) {
                this.delete_bookOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_bookOperationCompleted);
            }
            this.InvokeAsync("delete_book", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.delete_bookOperationCompleted, userState);
        }
        
        private void Ondelete_bookOperationCompleted(object arg) {
            if ((this.delete_bookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_bookCompleted(this, new delete_bookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/book_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] book_details([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("book_details", new object[] {
                        productid,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void book_detailsAsync(string productid, string host_email, string host_credential) {
            this.book_detailsAsync(productid, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void book_detailsAsync(string productid, string host_email, string host_credential, object userState) {
            if ((this.book_detailsOperationCompleted == null)) {
                this.book_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onbook_detailsOperationCompleted);
            }
            this.InvokeAsync("book_details", new object[] {
                        productid,
                        host_email,
                        host_credential}, this.book_detailsOperationCompleted, userState);
        }
        
        private void Onbook_detailsOperationCompleted(object arg) {
            if ((this.book_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.book_detailsCompleted(this, new book_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/search_books", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] search_books([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string input, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("search_books", new object[] {
                        type,
                        input,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void search_booksAsync(string type, string input, string host_email, string host_credential) {
            this.search_booksAsync(type, input, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void search_booksAsync(string type, string input, string host_email, string host_credential, object userState) {
            if ((this.search_booksOperationCompleted == null)) {
                this.search_booksOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_booksOperationCompleted);
            }
            this.InvokeAsync("search_books", new object[] {
                        type,
                        input,
                        host_email,
                        host_credential}, this.search_booksOperationCompleted, userState);
        }
        
        private void Onsearch_booksOperationCompleted(object arg) {
            if ((this.search_booksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_booksCompleted(this, new search_booksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/list_products", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] list_products([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string host_credential) {
            object[] results = this.Invoke("list_products", new object[] {
                        id,
                        host_email,
                        host_credential});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void list_productsAsync(string id, string host_email, string host_credential) {
            this.list_productsAsync(id, host_email, host_credential, null);
        }
        
        /// <remarks/>
        public void list_productsAsync(string id, string host_email, string host_credential, object userState) {
            if ((this.list_productsOperationCompleted == null)) {
                this.list_productsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlist_productsOperationCompleted);
            }
            this.InvokeAsync("list_products", new object[] {
                        id,
                        host_email,
                        host_credential}, this.list_productsOperationCompleted, userState);
        }
        
        private void Onlist_productsOperationCompleted(object arg) {
            if ((this.list_productsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.list_productsCompleted(this, new list_productsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sign_upCompletedEventHandler(object sender, sign_upCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sign_upCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sign_upCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sign_inCompletedEventHandler(object sender, sign_inCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sign_inCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sign_inCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void get_user_infoCompletedEventHandler(object sender, get_user_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void edit_user_infoCompletedEventHandler(object sender, edit_user_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class edit_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal edit_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void add_booksCompletedEventHandler(object sender, add_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void edit_booksCompletedEventHandler(object sender, edit_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class edit_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal edit_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void delete_bookCompletedEventHandler(object sender, delete_bookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_bookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_bookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void book_detailsCompletedEventHandler(object sender, book_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class book_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal book_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void search_booksCompletedEventHandler(object sender, search_booksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_booksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_booksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void list_productsCompletedEventHandler(object sender, list_productsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class list_productsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal list_productsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591